class Language:
    def __init__(self, lang):
        self.lang = lang
        self.msg = self.setMessages()

    def setMessages(self):
        if self.lang =="fr":
            return {
                'installAllDone': "Tous les Raspberry de votre réseau dj.zic ont été installés.",
                'installReboot': "Le système doit maintenant redémarrer",
                'installNoteC': "Référez-vous à",
                'installNoteB': "et avoir lancer le script post-install.",
                'installNoteA': "Toutes les fonctionnalités ne seront activées qu'après avoir installé dj.zic sur tous les appareils",
                'installInstr': "Et décompresser le fichier puis lancer l'installation sur l'appareil:",
                'installDest1': "du prochain Raspberry pi à installer.",
                'installDest': "dans le répertoire ",
                'installMove': "déplacer le fichier :",
                'installOnNext': "Pour installer l'appareil suivant",
                'installDeviceEnd': "L'installation de dj.zic sur cet appareil est terminée.",
                'installStart': "Procéder à l'installation?",
                'libDistance': "Librairie mise à jour",
                'lame': "Mp3 encoder installé.",
                'file':"Le fichier ",
                'piSnd':"Configuration du son pour",
                'piSndCard':"avec une carte son USB Audio.",
                'piSndVirtual':"avec la carte virtuelle alsa  (Aucune carte son détectée).",
                'noExist': "N'existe pas",
                'step7': "Configuration et activation des services",
                'sshAdded': "Clé publique ajoutée à authorized_keys",
                'installCert': "Les certificats sont insatllés.", 
                'step6': "Gestion des certificats",
                'venvDone': "L'environnement Python est créé et les scripts sont installés.",
                'venvNumpy': "Installation de numpy...",
                'venvRequests': "Installation de requests...",
                'venvPip': "Mise à jour de pip...",
                'venvModuleError': "Erreur durant l'instalaltion du module:",
                'setUpVenv': "L'environnement Python existe.",
                'createVenv': "L'environnement Python et les scripts associés sont installés",
                'step5': "Configuration de l'environnement virtuel Python et instalaltion des scripts.",
                'lameComlete': "Installation réussie",
                'faildedAt': "Echec lors de",
                'installing': "Installation",
                'make': "Compilation",
                'configureBuild': "Configuration du build",
                'extractingDone': "Le fichier est décompressé.",
                'extracting': "Décompression de ",
                'download': "Téléchargement de ",
                'downloadComplete': 'Téléchargement terminé.',
                'stepEncoder': "Installation des cdodecs mp3 (lame-3.100)",
                'icecast': "Installation du serveur de streaming",
                'wlan0Net': "L'interface réseau wlan0 est configurée.",
                'wlan1Net': "Les interfaces réseaux sont configurées: wlan0 (IBBS) et wlan1 (AP)",
                'dnsmasq': "dnsmasq est configuré.",
                'hostapd': "hostapd est configuré",
                'wpa': "wpa_supplicant est configuré.",
                'iptables': "Iptables est configuré.",
                'ipForward': "Ip forwarding activé",
                'step4':"Configuration du réseau mobile dj.zic",
                'addedToConf': " Rasperry(s) ajouté(s) au fichier de configuration: ",
                'notExist': "est inexistant",
                'directory': "répertoire",
                'permissionE': "Erreur de permissions",
                'permission': "Permissions changées pour ",
                'Replacements': "Modifications effectuées dans le fichier",
                'installSite': "Web site file installation.",
                'phpFpmError': "Erreur de configuration de: php-fpm",
                'phpFpmDone': "La configuration de php-fpm pour Lighttpd est effectuée.",
                'symlink': "Le lien symbolique n'a pas été créé",
                'socketNotFound': "Le Socket n'existe pas.",
                'phpVersionParse': "Impossible de déterminer la version de PHP",
                'phpVersion': "php version:",
                'phpNotFound': "PHP n'est pas installé ou ne figure pas dans le PATH",
                'phpfpmNotFound': "Lighttpd est introuvable.",
                'phpFpmConf': "Configuration de php-fpm pour php",
                'configPhp-fpm': "php-fpm est configuré.",
                'notFound': "Fichier introuvable.",
                'noPermission': "Pas de permission pour éditer ce fichier.",
                'lighttpdConfOk': "lighttpd.conf est maintenant configuré.", 
                'lighttpdsetUp': "Configuration de lighttpd.",
                'lighttpdConf': "Lighttpd est déjà configuré.",
                'step3': "Installation et configuration de l'environnement web.",
                'raspiConfigDone': "La configuration du son est effectuée.",
                'copyFailed': "Le fichier n'a pas pu être copié!",
                'copy': "Copie de",
                'raspiConfigSoundModule': "Configuration du module snd-aloop",
                'raspiConfigSound': "Installation du fichier de configuration de la carte son: asound.conf",
                'configSound': "Le fichier asound.conf est déjà installé.",
                'mofifyAliasConf': "Alias is configured",
                'aliasupdated': "Les alias de la carte sont configurés.",
                'raspiConfigAlias': "Configuration des alias de la carte son.",
                'firmwareNotUpdated': "Aucune optimisation du firmaware n'est nécéssaire.",
                'firmwareUpdated': "Le fichier firmware a été optimisé avec succès.",
                'raspiConfigFirmware': "Optimisation du firmware",
                'firmwareconf': "Le firmware du Raspberry pi est optimisé por Dj.zic",
                'step2': "Configuration système du Raspberry pi.",
                'icecast2Failed': "L'intallation de Icecast2 à échouée.",
                'icecast2Success': "Icecast2 a été installé avec succès.",
                'icecast2Install': "Installation de icecast2",
                'installPackages': "Les paquets nécéssaires sont déjà installés.",
                'packageFailed': "L'installation a échouée",
                'packageSuccess': "est dorrectement installé.",
                'upgradeAvailable': "Some packages are available for upgrade.",
                'checkUpdate': "Vérification des paquets à mettre à jour...",
                'wait': "Ce processus demander du temps, merci de patienter...",
                'execute' : "Running",
                'aptUpdated' : "Mise à jour terminée.",
                'aptUpdate' : "Le système est à jour.",
                'step1': "Mise à jour du système et installation des paquets requis.",
                'ap': "Point d'accès WI-FI",
                'installingMaster': "Installation du raspberry Principal ",
                'overview': "Apercu du réseau itinérant dj.zic à installer:",
                'choicesOptions': {'yes': ['o', 'oui'], 'no': ['n', 'non']},
                'choicesError': "Répondez par oui ou non.",
                'choices': "(oui/non): ",
                'installDevice': "Prévoyez-vous d'utiliser d'autres Raspberry Pi comme relais pour celui-ci ?",
                'installWlan': "Utilisez-vous des clés USB wifi?",
                'howManyRelay': "Combien de Relais allez-vous utiliser?",
                'soundCardDetected': "Carte son USB détectée.",
                'soundCardNotDetected': "Aucune carte son USB détectée",
                'quitNoSound': "Une carte son externe est requise.\n Fin du script d'installation.",
                'errorOccured': "Une erreur est survenue.",
                'clicompleted': "Commande exécuté avec succès",
                'cliFailed': "La commande a échouée",
                'solo': "Installation de dj.zic pour ce Raspberry."
            }
        else:
            return {
                'installAllDone': "All the Raspberry Pi of the dj.zic network are installed.",
                'installReboot': "The system must reboot",
                'installNoteC': "Refer to",
                'installNoteB': "and the post-install procedure done.",
                'installNoteA': "All dj.zic functionalities will only be available once all the devices have been installed",
                'installInstr': "Then on the device untar the file and run: ",
                'installDest1': "of the next Raspbery to install.",
                'installDest': "in the home directory ",
                'installMove': "Move the file :",
                'installOnNext': "To install on the next device",
                'installDeviceEnd': "Dj.zic is installed on this device",
                'installStart': "Proceed to install?",
                'libDistance': "Device lib created",
                'lame': "Mp3 encoder installed.",
                'file':"The File ",
                'piSnd':"Sound configuration for",
                'piSndCard':"with USB Audio card.",
                'piSndVirtual':"with Alsa virtual device (no physical Audio card detected).",
                'noExist': "Does not exist.",
                'step7': "Configuration et activation des services",
                'sshAdded' : "Public key added to authorized_keys",
                'installCert': "Certificates are installed.",
                'step6': "Certificates management",
                'venvDone': "Python virtual environment created and script installed successfully.",
                'venvNumpy': "numpy installation...",
                'venvRequests': "requests installation...",
                'venvPip': "Update pip...",
                'venvModuleError': "Error during python module installation:",
                'setUpVenv': "Python virtual env already exist.",
                'createVenv': "Python virtual env and associated scripts are installed",
                'step5': "Python virtual env configuration and scripts installation",
                'lameComlete': "Installation successful",
                'faildedAt': "Failed during",
                'installing': "Installing",
                'make': "Compiling",
                'configureBuild': "Configuring build",
                'extractingDone': "Extracting complete.",
                'extracting': "Extracting",
                'download': "Downloading ",
                'downloadComplete': 'Download complete',
                'stepEncoder': "Installation of mp3 encoder (lame-3.100)",
                'icecast': "Installation du serveur de streaming",
                'wlan0Net': "Network interface wlan0 is set",
                'wlan1Net': "Network interfaces set: wlan0 (IBBS) and wlan1 (AP)",
                'dnsmasq': "dnsmasq is set.",
                'hostapd': "hostapd is set.",
                'wpa': "wpa_supplicant is set.",
                'iptables': "iptables is set.",
                'ipForward': "Ip forwarding enabled",
                'step4':"Network configuration of the roaming network dj.zic",
                'addedToConf': " Rasperry(s) added to the configuration: ",
                'notExist': "does not exist",
                'directory': "directory",
                'permissionE': "Error changing permissions",
                'permission': "Permissions changed for ",
                'Replacements': "Modification successfuly done in the file:",
                'installSite': "Installation des fichiers du site",
                'phpFpmError': "Error configuring php-fpm.",
                'phpFpmDone': "Successfully configured php-fpm for Lighttpd.",
                'symlink': "The symlink could'nt be created.",
                'socketNotFound': "Socket not found.",
                'phpVersionParse': "Could not parse PHP version from",
                'phpVersion': "php version:",
                'phpNotFound': "PHP not installed or not in PATH",
                'phpfpmNotFound': "Lighttpd configuration directory not found",
                'phpFpmConf': "Configuration of php php-fpm.",
                'configPhp-fpm': "php-fpm is configured.",
                'notFound': "File not found.",
                'noPermission': "You do not have permission to edit this file.",
                'lighttpdConfOk': "lighttpd.conf successfully configrued", 
                'lighttpdsetUp': "Configuration of lighttpd.", 
                'lighttpdConf': "Lighttpd is already configured.",
                'step3': "Installation and configuration of the web environement.",
                'raspiConfigDone': "The sound configuraton is done.",
                'copyFailed': "The file can not be copied!",
                'copy': "Copy ",
                'raspiConfigSoundModule': "Enabling system module: snd-aloop",
                'raspiConfigSound': "Installation of the sound configuration file: asound.conf",
                'configSound': "The file asound.conf is installed.",
                'mofifyAliasConf': "Alias is configured",
                'aliasupdated': "Sound card aliases have been set-up.",
                'raspiConfigAlias': "Configuration of the sound card aliases.",
                'firmwareNotUpdated': "No firmware update is necessary.",
                'firmwareUpdated': "Firmware file has successfuly been optimized",
                'raspiConfigFirmware': "Firmlaware file optimization.",
                'firmwareconf': "Raspberry Pi firmware is already optimized for Dj.zic",
                'step2': "Raspberry pi system configuration.",
                'icecast2Failed': "Icecast2 install has failed.",
                'icecast2Success': "Icecast2 is successfully installed.",
                'icecast2Install': "Install icecast2",
                'installPackages': "Required packages are already installed.",
                'packageFailed': "install has failed",
                'packageSuccess': "is successfuly installed.",
                'upgradeAvailable': "Des paquets sont disponibles pour mise à niveau.",
                'checkUpdate': "Checking packages available for upgrade...",
                'wait': "This process can take a while, please wait...",
                'execute' : "Lancement de",
                'aptUpdated' : "System upgrade is done.",
                'aptUpdate' : "The system is up to date.",
                'step1': "System update and installation of required packages.",
                'ap': "WI-FI Acces Point",
                'installingMaster': "Install of the master raspberry",
                'overview': "Overview of the roaming dj.zic to install:",
                'choicesOptions': {'yes': ['y', 'yes'], 'no': ['n', 'no']},
                'choicesError': "Please answer yes or no.",
                'choices': "(yes/no): ",
                'installDevice': "Do you plan to use other Raspberry Pis as relays for this one?",
                'installWlan': "Will you use wifi USB card?",
                'howManyRelay': "How many Relay, do you want yo use?",
                'soundCardDetected':  "Soud Card detected.",
                'soundCardNotDetected': "No Sound card detected",
                'quitNoSound': "An external sound card is required.\n Quit.",
                'errorOccured': "Error occured",
                'clicompleted': "Command successful.",
                'cliFailed': "Command has failed.",
                'solo': "Solo dj.zic installation on this Raspberry."
            }
